2023-01-31 07:20:21.236 [main] INFO  com.iointel.mqtt.mqtt_app.App - App start
2023-01-31 07:20:21.683 [MQTT Call: MainClient] DEBUG com.iointel.mqtt.mqtt_app.MyMqttCallback - Messaged Delivered
2023-01-31 07:20:21.685 [MQTT Call: MainClient] INFO  com.iointel.mqtt.mqtt_app.MyMqttCallback - Messaged Published: Sample Message
2023-01-31 07:20:21.685 [MQTT Call: MainClient] INFO  com.iointel.mqtt.mqtt_app.MyMqttCallback - Subscribed Message: Sample Message
2023-01-31 07:20:21.686 [MQTT Call: MainClient] DEBUG com.iointel.mqtt.mqtt_app.MyMqttCallback - Message File Created
2023-01-31 07:20:21.688 [MQTT Call: MainClient] DEBUG com.iointel.mqtt.mqtt_app.MyMqttCallback - Message Bytes dumped into file: 0.txt
2023-01-31 07:44:50.647 [main] INFO  com.iointel.mqtt.mqtt_app.App - App start
2023-01-31 07:44:51.058 [MQTT Call: MainClient] DEBUG com.iointel.mqtt.mqtt_app.MyMqttCallback - Messaged Delivered
2023-01-31 07:44:51.059 [MQTT Call: MainClient] INFO  com.iointel.mqtt.mqtt_app.MyMqttCallback - Messaged Published: Sample Message
2023-01-31 07:44:51.059 [MQTT Call: MainClient] DEBUG com.iointel.mqtt.mqtt_app.MyMqttCallback - Subscribed Message: Sample Message
2023-01-31 07:44:51.060 [MQTT Call: MainClient] DEBUG com.iointel.mqtt.mqtt_app.MyMqttCallback - Message File Created
2023-01-31 07:44:51.062 [MQTT Call: MainClient] DEBUG com.iointel.mqtt.mqtt_app.MyMqttCallback - Message Bytes dumped into file: 0.txt
2023-01-31 09:14:16.589 [main] INFO  com.iointel.mqtt.mqtt_app.App - App start
2023-01-31 09:14:16.724 [main] ERROR com.iointel.mqtt.mqtt_app.App - Unable to connect to server (32103) - java.net.ConnectException: Connection refused: no further information
2023-01-31 09:14:16.727 [main] INFO  com.iointel.mqtt.mqtt_app.App - Reason 32104
2023-01-31 09:14:16.728 [main] INFO  com.iointel.mqtt.mqtt_app.App - Localized Message: Client is not connected
2023-01-31 09:14:16.728 [main] INFO  com.iointel.mqtt.mqtt_app.App - Cause: null
2023-01-31 09:14:16.728 [main] INFO  com.iointel.mqtt.mqtt_app.App - Exception: Client is not connected (32104)
2023-01-31 09:14:16.728 [main] ERROR com.iointel.mqtt.mqtt_app.App - Reason 32104
2023-01-31 09:14:16.729 [main] ERROR com.iointel.mqtt.mqtt_app.App - Client is not connected (32104)
